name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  server-tests:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: cd server && npm ci
      - name: Run tests
        run: cd server && npm test
        env:
          MONGODB_URI: mongodb://localhost:27017/among-us-irl-test
          JWT_SECRET: test-secret
          
  player-console-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: cd player-console && npm ci
      - name: Run tests
        run: cd player-console && npm test
        
  admin-console-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: cd admin-console && npm ci
      - name: Run tests
        run: cd admin-console && npm test
        
  e2e-tests:
    runs-on: ubuntu-latest
    needs: [server-tests, player-console-tests, admin-console-tests]
    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: |
          cd server && npm ci
          cd ../admin-console && npm ci
          cd ../player-console && npm ci
          cd ../e2e && npm ci
      - name: Start services
        run: |
          cd server && npm start &
          cd ../admin-console && npm start &
          cd ../player-console && npm start &
          sleep 30
      - name: Run Cypress tests
        run: cd e2e && npm run test:e2e
